---
- hosts: webserver
  become: yes

  vars:
    docker_compose_dir: /var/www/html
    backend_image: momousa1997/mern-backend
    frontend_image: momousa1997/mern-frontend
    ansible_python_interpreter: /usr/bin/python3

  tasks:
    - name: Ensure Docker is running
      service:
        name: docker
        state: started
        enabled: yes

    - name: Install Docker Compose
      get_url:
        url: "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-{{ ansible_system }}-{{ ansible_architecture }}"
        dest: /usr/local/bin/docker-compose
        mode: '0755'

    - name: Install Python pip
      apt:
        name: python3-pip
        state: present
        update_cache: yes

    - name: Install python3-venv
      apt:
        name: python3-venv
        state: present
        update_cache: yes

    - name: Create a Python virtual environment
      command: python3 -m venv /home/ubuntu/venv
      args:
        creates: /home/ubuntu/venv

    - name: Install Docker SDK for Python in virtual environment
      pip:
        requirements: /home/ubuntu/venv/requirements.txt
        virtualenv: /home/ubuntu/venv
      vars:
        ansible_python_interpreter: /home/ubuntu/venv/bin/python

    - name: Create Docker Compose Directory
      file:
        path: "{{ docker_compose_dir }}"
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: '0755'

    - name: Copy docker-compose.yml to Server
      copy:
        src: ./docker-compose.yml
        dest: "{{ docker_compose_dir }}/docker-compose.yml"
        owner: ubuntu
        group: ubuntu
        mode: '0644'

    - name: Pull Latest Backend Image
      community.docker.docker_image:
        name: "{{ backend_image }}"
        source: pull

    - name: Pull Latest Frontend Image
      community.docker.docker_image:
        name: "{{ frontend_image }}"
        source: pull

    - name: Stop Running Docker Containers
      docker_compose:
        project_src: "{{ docker_compose_dir }}"
        state: absent

    - name: Start Docker Containers
      docker_compose:
        project_src: "{{ docker_compose_dir }}"
        state: present
      register: docker_compose_output

    - name: Debug Docker Compose Output
      debug:
        var: docker_compose_output

    - name: Check Docker Compose Logs
      shell: |
        cd {{ docker_compose_dir }}
        docker-compose logs
      register: docker_compose_logs

    - name: Debug Docker Compose Logs
      debug:
        var: docker_compose_logs.stdout_lines
"
